# Generated by Django 5.1.4 on 2026-09-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrun",
            name="progress_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="export_progress_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="marked_done",
            field=models.BooleanField(default=False),
        ),
    ]
