# Generated by Django 5.1.4 on 2026-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_detectionrun_progress_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneboundary",
            name="after_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sceneboundary",
            name="after_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sceneboundary",
            name="before_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sceneboundary",
            name="before_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
