# Generated by Django 5.1.4 on 2026-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_sceneboundary_after_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="export_progress_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scene",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
