# Generated by Django 5.1.4 on 2026-09-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_scene_export_progress_percent_scene_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='encode_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
