# Generated by Django 5.1.4 on 2026-09-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_scene_encode_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='videos.video'),
        ),
    ]
