# Generated by Django 5.1.4 on 2026-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_duplicate_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='encode_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
