# Generated by Django 5.1.4 on 2026-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_scene_encode_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recorded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
